# Generated by Django 3.2.4 on 2022-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlluserData',
            new_name='Allusers',
        ),
        migrations.AddField(
            model_name='vendor',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
