# Generated by Django 3.2.4 on 2022-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221029_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='total_orders',
            field=models.IntegerField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
