# Generated by Django 3.2.4 on 2022-10-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vendor_total_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='total_orders',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='total_raters',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='total_rating',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
