# Generated by Django 3.2.4 on 2022-10-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221029_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
    ]
