# Generated by Django 3.2.4 on 2022-10-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_vendor_fooditems_vendorusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/food/<django.db.models.fields.CharField>'),
        ),
    ]
