# Generated by Django 3.2.4 on 2022-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fooditems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/food/'),
        ),
    ]
